// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD4MP8u4xdscsuzDJEMLw49GYVudt18bvI',
    appId: '1:235807416604:web:6d663f3918ab51a4aa9ad9',
    messagingSenderId: '235807416604',
    projectId: 'bismillahdb-223d7',
    authDomain: 'bismillahdb-223d7.firebaseapp.com',
    storageBucket: 'bismillahdb-223d7.appspot.com',
    measurementId: 'G-2WWVK32ZZG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBIQyRuo7Zgqr7ecwTo95_0odjzU-QQFGQ',
    appId: '1:235807416604:android:71afc81c05a28269aa9ad9',
    messagingSenderId: '235807416604',
    projectId: 'bismillahdb-223d7',
    storageBucket: 'bismillahdb-223d7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBXtKnTdAwnUPctc494mOcxMa0EDBjvUxM',
    appId: '1:235807416604:ios:da6c8d0d1244a686aa9ad9',
    messagingSenderId: '235807416604',
    projectId: 'bismillahdb-223d7',
    storageBucket: 'bismillahdb-223d7.appspot.com',
    iosBundleId: 'com.example.ebookApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBXtKnTdAwnUPctc494mOcxMa0EDBjvUxM',
    appId: '1:235807416604:ios:da6c8d0d1244a686aa9ad9',
    messagingSenderId: '235807416604',
    projectId: 'bismillahdb-223d7',
    storageBucket: 'bismillahdb-223d7.appspot.com',
    iosBundleId: 'com.example.ebookApp',
  );
}
